name="opentitan"
default_config = "test"
#base_repos=["opentitan", "verilator"]
base_repos=[]
configs=["test", "all"]
workflow="readonly"
logging="Yes"
stages = ["download", "configure", "install"]

[env]
TOOLS_DIR="%GRIP_ROOT_PATH%/tools"
BUILD_DIR="%GRIP_ROOT_PATH%/build"

[config.test]
#repos=["verilator"]
repos=["toolchains", "opentitan"]

[config.all]
repos=["verilator", "openocd", "opentitan"]

[repo.opentitan]
url="https://github.com/lowRISC/opentitan.git"
path="opentitan"
branch="master"
workflow="readonly"
oc_configure={exec="TOOLCHAIN_PATH=%TOOLS_DIR% BUILD_ROOT=%BUILD_DIR% ./meson_init.sh -f"}

[repo.riscv-gnu-toolchain]
url="https://github.com/riscv/riscv-gnu-toolchain"
path="riscv-gnu-toolchain"
download={exec="git submodule update --init --recursive"}
configure={requires=["download"], exec="./configure --prefix=%TOOLS_DIR% --with-abi=ilp32 --with-arch=rv32imc --with-cmodel=medany"}

[repo.toolchains]
url = "https://github.com/atthecodeface/toolchain_building.git"
path = "toolchains"
doc = """
The repository is used here to build cross-compiler, linker and assembler for RISC-V32 Elf,
i.e. not a Linux-specific libc; this allows non-OS applications/tests to be built

"""
configure-riscv32-unknown-elf.satisfies="configure"
install-riscv32-unknown-elf.satisfies="install"

[repo.toolchains.configure-riscv32-unknown-elf.env]
# GCC_CONFIG      = "--with-newlib=yes --disable-libssp"
GCC_CONFIG      = "--with-abi=ilp32  --with-arch=rv32imc --enable-languages=c,c++ --with-system-zlib --with-newlib --with-sysroot=%TOOLS_DIR%/sysroot --disable-shared --disable-threads --disable-tls --disable-libmudflap --disable-libssp --disable-libquadmath --disable-libgomp --disable-nls --disable-tm-clone-registry "
BINUTILS_CONFIG = "--disable-gold --enable-plugins --disable-werror --disable-gdb --disable-sim --disable-libdecnumber --disable-readline"

[repo.verilator]
url="http://git.veripool.org/git/verilator"
path="verilator"
branch="v4.028"
workflow="readonly"
configure={exec="autoconf && ./configure --prefix=%TOOLS_DIR%/verilator"}
install={exec="make -j6 && make install",requires=["configure"]}

[repo.openocd]
url="https://github.com/riscv/riscv-openocd.git"
path="riscv-openocd"
workflow="readonly"
configure={exec="./bootstrap && mkdir -p %BUILD_DIR%/build-openocd && cd %BUILD_DIR%/build-openocd && %GRIP_REPO_PATH%/configure --enable-ftdi --enable-verbose-jtag-io --disable-vsllink --enable-remote-bitbang --prefix=%TOOLS_DIR%/openocd"}
install={wd="%BUILD_DIR%/build-openocd", exec="make -j4 && make install", requires=["configure"]}

